name: 'Tests'

on: ["push"]

jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go 1.25.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Install dependencies
        run: go mod download

      - name: Build service
        run: |
          go build -o ./payment ./cmd/payment

      - name: Run service
        run: |
          nohup ./payment --config=./config/tests.yaml &

      - name: Run tests
        run: go test -v ./tests
